version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  logger:
    build: ./logger
    ports:
      - "5002:5002"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"          
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
      - PORT=5000
    depends_on:
      - postgres
      - logger
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"           
    environment:
      - BACKEND_URL=http://backend:5000/api/data
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
