name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd backend
          pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: khushikande26/backend:latest
          context: ./backend

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: khushikande26/frontend:latest
          context: ./frontend

      - name: Build and push logger image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: khushikande26/logger:latest
          context: ./logger
